server:
  port: 8080

spring:
  application:
    name: en-study-remind
  datasource:
    url: jdbc:h2:file:./db/english;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # 开启 H2 网页控制台，访问 http://localhost:8080/h2-console
      path: /h2-console
      settings:
        web-allow-others: true # 允许远程访问 H2 控制台
  jpa:
    hibernate:
      ddl-auto: none # 自动建表
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: always # 每次启动应用时都执行初始化脚本
      schema-locations: classpath:sql/schema.sql # 初始化脚本位置
      continue-on-error: true # 初始化脚本执行失败时是否继续执行

# --- 企业微信配置 (请在此处填入你的参数) ---
weChat:
# 企业微信机器人配置
  groupKey: "?"